alpha_entr: 0
assert_max_count: false
base_log: <put your log directory>
canvas_size: 16
checkpoint_step: best
cl_weight: 1
classify: true
ddp: false
edge_att_weight: 0
edge_rep_weight: 0
evaluate: true
force_overwrite: true
force_py_backup: false
freeze_gin: false
gin_last_act: false
inner_lr: 0.5
inter_weight: 1
intra_weight: 1
is_inner_loop: false
is_ixz: false
is_lookup_mask: false
ixz_gin_mean: true
ixz_weight: 0.1
learning_rate: 0.0001
load_latest: true
log_dir: null
lr_scheduler_type: None
max_count: 235
max_n_distractors: 1
min_n_distractors: 1
mlp_concat: true
momentum: 0.9
multi_head_rel: false
n_examples: 2400
num_augs: 2
num_epochs: 10000
num_inner_loop: 5
num_objs: 3
num_rels: 3
obj_dim: 100
padding_objs: 4
pkl_name: data_rec.p
print_interval: 20
print_interval2: 10
print_interval3: 25
random_seed: 0
rel_dim: 20
reparam_mode: diag
run_edge_dist: true
run_id: gin-MLP_16x16_classify_noalp_no-gin_last_act-3obj1dist
save_interval: 25
show_tsne: false
softmax_rel: false
supervised: false
task_batch_size: 168
total_tasks: 6
total_tr_examples: 8460
train_aug: true
train_data_shuffle: true
train_drop_last: true
train_mask_shuffle: true
weight_decay: 0
workers: 11
write_tb_imgs: false
